Added official guestbook example
kedgeproject/kedge pull request #538
Opened 2017-12-19 10:47 UTC by surajnarwade

* guestbook-official is referred from https://kubernetes.io/docs/tutorials/stateless-application/guestbook/
  This will work with Kubernetes only

* guestbook-go is referred from https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook-go
  This will work with both Kubernetes as well as OpenShift

2017-12-20 15:53 UTC, cdrage requested changes

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-go/README.md
> +
please remove all of these newlines ^^

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-go/redis-master.yml
> +
remove this newline

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-go/redis-master.yml
> +#replicas: 1
remove comment

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-go/guestbook.yml
> +#replicas: 3
remove commented out code

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-go/redis-slave.yml
> +#replicas: 2
remove commented out line

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-official/README.md
> +
remove newlines

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-official/frontend.yaml
> +
remove newline

2017-12-20 15:53 UTC, cdrage commented on examples/guestbook-official/redis-master.yaml
> +
remove newline

2017-12-20 16:29 UTC, cdrage commented
Tested guestbook-official against Kubernetes :+1: 
Tested guestbook-go against Kubernetes :+1: 
Tested guestbook-go against OpenShift :+1: 

After you've fixed the extra newlines / commented out lines, feel free to merge in! :100:  Thanks @surajnarwade

2017-12-20 17:46 UTC, cdrage commented on examples/guestbook-official/frontend.yaml
> +  type: NodePort
we should use loadbalancer rather than nodeport here

2017-12-20 17:47 UTC, cdrage commented
@surajnarwade Just realized that NodePort is being used... this should use LoadBalancer: https://github.com/kubernetes/examples/blob/master/guestbook-go/guestbook-service.json

from the official example ^^

2017-12-20 17:57 UTC, cdrage commented
another comment: they all need to be `.yaml` not `.yml`

2017-12-21 02:07 UTC, surajnarwade commented
@cdrage , oh I forgot, I used `NodePort` for my convenience 
Updated with suggested changes

2017-12-21 16:32 UTC, cdrage requested changes
@surajnarwade one last change

2017-12-21 16:32 UTC, cdrage commented on examples/guestbook-go/redis-slave.yaml
> +#replicas: 2
remove commented out line

2018-01-03 06:28 UTC, kadel requested changes
Containers on openshift are running, but redis replication is not working. And Guestbook is also not working (can't save messages)

2018-01-03 06:50 UTC, surajnarwade commented
@kadel guestbook-go is not working for you ?

2018-01-03 12:00 UTC, kadel commented
when I try to save message to guestbook i get following error in guestbook pod
```
[negroni] Started GET /rpush/guestbook/fff
--
  | [negroni] PANIC: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
  | goroutine 5 [running]:
  | github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x7f6169388a90, 0xc82021ffc0, 0xc8200b6ea0)
  | /go/src/github.com/codegangsta/negroni/recovery.go:34 +0xe9
  | panic(0x76aee0, 0xc82030bff0)
  | /usr/local/go/src/runtime/panic.go:426 +0x4e9
  | main.HandleError(0x0, 0x0, 0x7f6169349608, 0xc82030bff0, 0x0, 0x0)
  | /go/src/github.com/GoogleCloudPlatform/kubernetes/examples/guestbook-go/_src/main.go:71 +0x59
  | main.ListPushHandler(0x7f6169388a90, 0xc82021ffc0, 0xc8202c0a80)
  | /go/src/github.com/GoogleCloudPlatform/kubernetes/examples/guestbook-go/_src/main.go:47 +0x192
  | net/http.HandlerFunc.ServeHTTP(0x8a8270, 0x7f6169388a90, 0xc82021ffc0,
```


all redist-slave pods are showing:
```

[7] 03 Jan 11:58:16.042 * Connecting to MASTER redis-master:6379
--
  | [7] 03 Jan 11:58:16.044 * MASTER <-> SLAVE sync started
  | [7] 03 Jan 11:58:16.044 * Non blocking connect for SYNC fired the event.
  | [7] 03 Jan 11:58:16.044 # Error reply to PING from master: '-MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.'
```

redis-master

```

[1] 03 Jan 11:51:54.310 * The server is now ready to accept connections on port 6379
--
  | [1] 03 Jan 11:52:29.677 * Slave 172.17.0.7:6379 asks for synchronization
  | [1] 03 Jan 11:52:29.677 * Full resync requested by slave 172.17.0.7:6379
  | [1] 03 Jan 11:52:29.677 * Starting BGSAVE for SYNC with target: disk
  | [1] 03 Jan 11:52:29.678 * Background saving started by pid 9
  | [9] 03 Jan 11:52:29.678 # Failed opening .rdb for saving: Permission denied
  | [1] 03 Jan 11:52:29.720 # Background saving error
  | [1] 03 Jan 11:52:29.720 # Connection with slave 172.17.0.7:6379 lost.
  | [1] 03 Jan 11:52:29.720 # SYNC failed. BGSAVE child returned an error


```

2018-01-03 16:29 UTC, cdrage commented
I've been using this example fine, have you been waiting until redis-slave comes up (kubectl get po) and then testing the application on Guestbook / browser? I ran into the same issue of trying to save messages before it came up.

I'm using: https://github.com/kedgeproject/kedge/pull/554/files and it works.


@surajnarwade Can you check / compare between your example and https://github.com/kedgeproject/kedge/pull/554/files and see if it helps solve any issues you may be encountering?

2018-01-03 16:31 UTC, cdrage requested changes
When I commented I said to remove the line, not un-comment :) This should fix any issues that @kadel was having. This modification works for me (see: https://github.com/kedgeproject/kedge/pull/554/files )

2018-01-03 16:31 UTC, cdrage commented on examples/guestbook-go/guestbook.yaml
> +replicas: 3
remove replicas

2018-01-03 16:31 UTC, cdrage commented on examples/guestbook-go/redis-master.yaml
> +replicas: 1
remove replicas

2018-01-03 16:31 UTC, cdrage commented on examples/guestbook-go/redis-slave.yaml
> +replicas: 2
remove replicas

2018-01-03 16:31 UTC, cdrage commented on examples/guestbook-official/frontend.yaml
> +replicas: 3
remove replicas (why is there 3?)

2018-01-03 16:31 UTC, cdrage commented on examples/guestbook-official/redis-master.yaml
> +replicas: 1
remove replicas

2018-01-03 16:31 UTC, cdrage commented on examples/guestbook-official/redis-slave.yaml
> +replicas: 2
remove replicas

2018-01-05 09:52 UTC, surajnarwade commented
@kadel can you try once again ?

2018-01-05 10:28 UTC, kadel commented
guestbook-go is still not working on OpenShift. (works if root is enabled, but that is not what we want)

redis-master:
```
[8] 05 Jan 10:16:19.629 # Failed opening .rdb for saving: Permission denied
```

Haven't look at it closer, but I suspect that there are some problems with file or directory permissions. Maybe adding PVC where redis data will be saved might help?

2018-01-16 09:23 UTC, surajnarwade commented
I tried,

```
$ kedge apply -f examples/guestbook-go/
W0116 14:31:22.724313   24483 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
service "guestbook" created
W0116 14:31:22.943018   24492 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
deployment "guestbook" created
W0116 14:31:23.152870   24503 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
service "redis-master" created
W0116 14:31:23.365897   24514 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
deployment "redis-master" created
W0116 14:31:23.559956   24524 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
service "redis-slave" created
W0116 14:31:23.757599   24533 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
deployment "redis-slave" created
```

I got,

```
$ oc get pods
NAME                            READY     STATUS    RESTARTS   AGE
guestbook-871169334-50bbl       1/1       Running   0          19m
redis-master-2082469664-f1h3v   1/1       Running   0          19m
redis-slave-3332111353-tkhpc    1/1       Running   0          19m
```

No addons is enabled,

```
$ minishift addons list
- admin-user     : disabled   P(0)
- anyuid         : disabled   P(0)
- registry-route : disabled   P(0)
- xpaas          : disabled   P(0)
```

2018-01-16 09:24 UTC, surajnarwade commented
@kadel , examples is working fine on my system :D

2018-01-17 09:49 UTC, kadel commented
It is nice that pods are running, but that doesn't mean that application is working!

Have you actually tried to access the guestbook web and save some message?
Have you looked at logs and verified that redis is working?

2018-01-18 10:18 UTC, surajnarwade commented
@kadel you are right, only guestbook is running but redis is failing

2018-02-15 08:01 UTC, surajnarwade commented
what should we do about this ?

2018-02-21 01:34 UTC, cdrage commented
@surajnarwade Does it currently work? I'd say another review and we can try and get this in?

2019-09-19 14:19 UTC, closed without merging