Added automatic port info detection from Dockerfile
kedgeproject/kedge pull request #588
Opened 2018-02-06 10:11 UTC by surajnarwade

Experimental

2018-02-06 14:08 UTC, surajssd commented on cmd/init.go
> +			_, err = os.Stat("Dockerfile")
this will pickup dockerfile relative to kedge binary not the project root dir

2018-02-06 14:09 UTC, surajssd commented on cmd/init.go
> +			_, err = os.Stat("Dockerfile")
parameterize the dockerfile name to a variable and use it everwhere

2018-02-06 14:10 UTC, surajssd commented on cmd/init.go
> +				fmt.Println(fileName, "is not present")
i am not sure what fileName is here?

2018-02-06 14:11 UTC, surajssd commented on cmd/init.go
> +	"github.com/asottile/dockerfile"
Q: no need to here?

2018-02-07 05:58 UTC, surajssd requested changes

2018-02-07 05:58 UTC, surajssd commented on cmd/init.go
> +				a, err := dockerfile.ParseFile("Dockerfile")
the parsing should remain generic, as in whether to parse or not should be governed by other factors(like a flag or something) not on whether port info is provided.

2018-02-07 05:58 UTC, surajssd commented on cmd/init.go
> +				a, err := dockerfile.ParseFile("Dockerfile")
in this section then only extract port info

2018-02-07 06:59 UTC, surajnarwade commented on cmd/init.go
> +	"github.com/asottile/dockerfile"
done vendoring

2018-02-15 08:28 UTC, surajnarwade commented
There is conflict between docker version of `dockerfile` and `kedge` :(

2019-09-19 14:19 UTC, closed without merging